#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : WSGIProxy2
Version  : 0.4.4
Release  : 31
URL      : http://pypi.debian.net/WSGIProxy2/WSGIProxy2-0.4.4.tar.gz
Source0  : http://pypi.debian.net/WSGIProxy2/WSGIProxy2-0.4.4.tar.gz
Summary  : A WSGI Proxy with various http client backends
Group    : Development/Tools
License  : MIT
Requires: WSGIProxy2-python3
Requires: WSGIProxy2-license
Requires: WSGIProxy2-python
Requires: requests
Requires: six
Requires: urllib3
BuildRequires : WebOb
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : tox
BuildRequires : virtualenv

%description
============

%package license
Summary: license components for the WSGIProxy2 package.
Group: Default

%description license
license components for the WSGIProxy2 package.


%package python
Summary: python components for the WSGIProxy2 package.
Group: Default
Requires: WSGIProxy2-python3
Provides: wsgiproxy2-python

%description python
python components for the WSGIProxy2 package.


%package python3
Summary: python3 components for the WSGIProxy2 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the WSGIProxy2 package.


%prep
%setup -q -n WSGIProxy2-0.4.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1529094071
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/WSGIProxy2
cp COPYING %{buildroot}/usr/share/doc/WSGIProxy2/COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/WSGIProxy2/COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
